---
- name: install base packages
  apt: pkg={{ item }} state=latest install_recommends=no update_cache=yes
  with_items:
    - build-essential
    - libxml2-dev
    - libpq-dev
    - libbz2-dev
    - libtool
    - automake
    - libproj-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-thread-dev
    - libexpat-dev
    - gcc
    - proj-bin
    - libgeos-c1
    - libgeos++-dev
    - libexpat-dev
    - php5
    - php-pear
    - php5-pgsql
    - php5-json
    - php-db
    - libapache2-mod-php5
    - wget

- include: postgres.yml 

# create vhost + configure nominatim website
- include: apache.yml

- name: create nominatim directories
  file: path="{{item}}"  owner={{ nominatim_user }} group={{ nominatim_user }} state=directory
  with_items:
    - "{{ nominatim_base_dir }}"
    - "/var/log/nominatim"
    - "{{ nominatim_web_dir }}"

- name: check if Nominatim dir exists
  shell: test -d {{ nominatim_install_dir }}
  register: nominatim_exists
  check_mode: no
  ignore_errors: yes
  changed_when: false

- name: dl nominatim files
  get_url: 
    url: http://www.nominatim.org/release/Nominatim-{{ nominatim_version }}.tar.bz2
    dest: /tmp/
  when: nominatim_exists|failed

- name: decompress nominatim files
  unarchive:
    src: /tmp/Nominatim-{{ nominatim_version }}.tar.bz2
    dest: "{{ nominatim_base_dir }}/"
    copy: no
    owner: {{ nominatim_user }}
    group: {{ nominatim_user }}
  when: nominatim_exists|failed

- name: nominatim config local file
  template: src=local.php.j2 dest={{ nominatim_install_dir }}/settings/local.php

- name: check if configure is needed
  shell: cd {{ nominatim_install_dir }} && test -f config.status && test -x ./module/nominatim.so
  register: nominatim_configured
  check_mode: no
  ignore_errors: yes
  changed_when: false

- name: configure
  shell: ./configure && make clean && make 
  args: 
    chdir: "{{ nominatim_install_dir }}/"
  become: true
  become_user: {{ nominatim_user }}
  when: nominatim_configured|failed


- name: stat on planet-latest 
  shell: ls /srv/planet-latest.osm.pbf -s
  register: dl_planet
  check_mode: no
  ignore_errors: yes
  changed_when: false

- name: dl nominatim planet data
  get_url: 
    url: http://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-latest.osm.pbf
    dest: /srv/
  tags: 
    - planet
  when: dl_planet|failed

# executed during the setup.php script
- name: dl nominatim gb postcodes
  get_url:
   url: http://www.nominatim.org/data/gb_postcode_data.sql.gz
   dest: "{{ nominatim_install_dir }}/data/"
  become: true
  become_user: {{ nominatim_user }}
  when: dl_planet|failed 

- name: import planet
  shell: nohup ./utils/setup.php --osm-file /srv/planet-latest.osm.pbf --all --osm2pgsql-cache 28000 2>&1 > /var/log/nominatim/importplanet.log & 
  args:
      chdir: "{{ nominatim_install_dir }}/"
  become: true
  become_user: {{ nominatim_user }}
  when: dl_planet|failed 


- name: check if dl wiki data is needed
  shell: cd {{ nominatim_install_dir }}/data/ && test -f wikipedia_article.sql.bin && test -f wikipedia_redirect.sql.bin 
  register: dl_wiki
  check_mode: no
  ignore_errors: yes
  changed_when: false
  
- name: dl nominatim other data sources
  get_url:
   url: http://www.nominatim.org/data/{{ item }}
   dest: "{{ nominatim_install_dir }}/data/"
  with_items:
   - wikipedia_article.sql.bin
   - wikipedia_redirect.sql.bin
  become: true
  become_user: {{ nominatim_user }}
  when: dl_wiki|failed

- name: import special phrases
  shell: ./utils/specialphrases.php --{{item}} > data/specialphrases_{{item}}.sql && psql -d nominatim -f data/specialphrases_{{item}}.sql
  with_items:
    - countries
    - wiki-import 
  args:
      chdir: "{{ nominatim_install_dir }}/"
  become: true
  become_user: {{ nominatim_user }}
  when: dl_wiki|failed

- name: check if create website is needed
  shell: cd {{ nominatim_web_dir }} && test -f index.php 
  register: create_website
  check_mode: no
  ignore_errors: yes
  changed_when: false

- name: configure osm website
  shell: "{{ nominatim_install_dir }}/utils/setup.php --create-website {{ nominatim_web_dir }}"
  become: true
  become_user: {{ nominatim_user }}
  when: create_website|failed


